### ISSUE TITLE
The @property methods of injected dependencies doesn't work

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/web-poet#11]
While exploring @victor-torres's suggestion in #10 , I've noticed that the injected dependencies methods decorated with a `@property` method doesn't work.

So, given the reproducible code snippet below, it's met with:

```
# stacktrace lines truncated

 File "/Users/path/omitted/site-packages/scrapy/utils/response.py", line 21, in get_base_url
    text = response.text[0:4096]
TypeError: 'property' object is not subscriptable
```

```Python
from scrapy import Spider
from scrapy.http import Response
from scrapy.linkextractors import LinkExtractor
from web_poet.pages import ItemWebPage

class QuotesListingPage(ItemWebPage):
    scrapy_response = Response

    def to_item(self):
        return {
            'site_name': self.css('h1 a::text').get(),
            'author_links': LinkExtractor(
                restrict_css='.author + a').extract_links(self.scrapy_response),
        }

class QuotesBaseSpider(Spider):
    name = 'quotes'
    allowed_domains = ['http://quotes.toscrape.com/']
    start_urls = ['http://quotes.toscrape.com//']

    def parse(self, response, page: QuotesListingPage):
        return page.to_item()
```

I think this bug blocks us a bit since I'm currently creating a Provider for `ResponseMeta` since our Page Objects needs some information stored there.

**Comment by victor-torres** [comment]
Thank you for reporting, @BurnzZ.

The example I gave you is wrong in two ways:

- it should be `scrapy_response: Response` instead of `scrapy_response = Response` (this is why you're getting the property object instead of a value)
- Scrapy dependencies should not be injected into Page Objects but into Providers only, so it wouldn't work after this fix anyway 

I'll close this issue and we can get back to the discussion on #10, alright?
